export const SERVICIOS_HOSPITALARIOS = [
  "Emergencia",
  "Bienestar Magisterial",
  "UCIN ISBM",
  "UCI ISBM",
  "Cirugía Hombres 1",
  "Cirugía Mujeres 1",
  "Cirugía Cardiovascular",
  "Neurocirugia",
  "Dolor y Cuidados Paliativos",
  "UCIN Adultos",
  "UCIN Aislados",
  "UCIN Crónicos",
  "Medicina Interna Hombres 1",
  "Medicina Interna Hombres 2",
  "Medicina Interna Hombres 3",
  "Medicina Interna Mujeres 1",
  "Medicina Interna Mujeres 2",
  "Medicina Interna Mujeres 3",
  "Medicina Interna Cardiología",
  "Medicina Interna Hematología",
  "Medicina Interna Aislado",
  "Medicina Interna Oncologia",
  "UCI General I",
  "UCI General II",
  "UCI Aislados",
  "UCI Cardiovascular",
  "UCI Extracorpórea",
  "UCI Quirúrgica",
  "UCI Neurointensivos",
  "UCI Coronarios y Postquirúrgicos (UCCP)",
  "Evaluación y Observación Médica",
  "Quimioterapia Ambulatoria",
  "Terapia Intervencionista Endovascular",
  "Dialisis Peritoneal",
] as const;

export type ServicioHospitalario = (typeof SERVICIOS_HOSPITALARIOS)[number];
